public class MathOperations {

    public static Integer addNum(Integer num1, Integer num2){
    
        Integer addition;

        addition = num1 + num2;
        system.debug('Addition ' +addition);
        
        return addition;
    }
	public static Integer subNum(Integer num1, Integer num2){
    
        Integer subtraction;

        subtraction = num1 - num2;
        system.debug('Sub ' +subtraction);
        
        return subtraction;
    }
}